parameters:
    defaults:
        engine:
          timeout: 10
          ssl_verifypeer: false
          useragent: "LeaseWeb API Caller"
          followlocation: true
          sslversion: 3

    _:
        endpoint:
        format:   passthrough
        replace_engine: false
