parameters:
    api_caller_factory.class: Lsw\ApiCallerBundle\Factory\ApiCallerFactory
    api_call_logger.class: Lsw\ApiCallerBundle\Logger\ApiCallLogger
    api_caller.data_collector.class: Lsw\ApiCallerBundle\DataCollector\ApiCallDataCollector
    api_caller.data_collector.template: "LswApiCallerBundle:Collector:api"

services:
    api_caller:
        class: %api_caller_factory.class%
        arguments: [%api_caller.options%, @api_call_logger]
    api_call_logger:
        class: %api_call_logger.class%
        arguments: [@logger]
        tags:
            - { name: monolog.logger, channel:api_caller }
    api_caller.data_collector:
        class: %api_caller.data_collector.class%
        arguments: [@api_call_logger]
        tags:
            - { name: data_collector, template: %api_caller.data_collector.template%, id:"api"}